# 운영 환경 설정
spring:
  data:
    mongodb:
      uri: mongodb://admin:${MONGO_PASSWORD}@mongo-server:27017/portfolio

server:
  port: 8080

# 운영 환경 로깅 (최소)
logging:
  level:
    org.springframework.data.mongodb: WARN
    com.portfolio.portfolio_website: INFO
    root: WARN